; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W1F1AL	; Alternate level layout
	.word W1F1AO	; Alternate object layout
	.byte LEVEL1_SIZE_15 | LEVEL1_YSTART_140
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_02 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(2) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_FORTRESS | LEVEL5_TIME_300

	.byte $14, $EC, $07, $79, $E1, $41, $01, $16, $E3, $E4, $01, $16, $E7, $E4, $08, $74
	.byte $EF, $31, $00, $79, $E5, $41, $01, $EE, $58, $20, $61, $00, $3F, $70, $69, $00
	.byte $3F, $70, $79, $00, $41, $70, $13, $01, $D2, $15, $0C, $62, $0E, $0D, $E4, $02
	.byte $92, $06, $C0, $03, $01, $EF, $02, $98, $10, $A0, $93, $0E, $B0, $90, $12, $90
	.byte $92, $12, $C0, $19, $15, $E1, $02, $18, $15, $C2, $0E, $16, $E4, $00, $0D, $0D
	.byte $C2, $01, $12, $E6, $04, $08, $12, $D0, $08, $16, $D0, $2D, $16, $05, $88, $14
	.byte $B0, $0A, $0E, $00, $0D, $19, $71, $0D, $06, $71, $03, $20, $EF, $02, $13, $20
	.byte $D2, $03, $26, $EF, $04, $13, $26, $D0, $0E, $2C, $71, $16, $21, $62, $0B, $24
	.byte $00, $93, $28, $B0, $E0, $38, $42, $E2, $38, $E0, $93, $16, $80, $8F, $2E, $90
	.byte $13, $2A, $D0, $11, $2C, $71, $11, $2C, $81, $14, $2C, $71, $14, $2C, $81, $16
	.byte $33, $62, $12, $36, $E8, $02, $11, $36, $C2, $0E, $37, $00, $30, $33, $60, $30
	.byte $3B, $60, $0D, $33, $D1, $0D, $3B, $D0, $01, $33, $EB, $01, $01, $3B, $EB, $00
	.byte $91, $2E, $C0, $8A, $3D, $C0, $88, $3D, $C0, $01, $20, $EF, $02, $01, $26, $EF
	.byte $04, $01, $01, $EF, $02, $0E, $41, $EC, $02, $0D, $41, $C2, $30, $4B, $60, $01
	.byte $4B, $EB, $00, $0D, $4B, $D0, $0A, $31, $08, $0B, $4E, $00, $30, $51, $60, $0D
	.byte $51, $D0, $01, $51, $EB, $00, $0E, $45, $71, $0E, $53, $72, $15, $4A, $62, $0A
	.byte $42, $91, $6A, $42, $64, $E3, $38, $E4, $01, $54, $E6, $06, $08, $54, $D6, $E5
	.byte $48, $73, $E4, $48, $73, $6B, $59, $E0, $16, $57, $00, $0A, $5E, $91, $6A, $5E
	.byte $54, $FF