; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W1F3BL	; Alternate level layout
	.word W1F3BO	; Alternate object layout
	.byte LEVEL1_SIZE_15 | LEVEL1_YSTART_040
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_11 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_02 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(2) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_CASTLE | LEVEL5_TIME_400

	.byte $E3, $21, $31, $E5, $21, $07, $E8, $21, $31, $E9, $21, $8A, $EB, $21, $31, $EC
	.byte $21, $30, $ED, $21, $31, $EE, $58, $20, $FF