; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_08 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_FREE
	.byte LEVEL4_BGBANK_INDEX(28) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $9A, $01, $6A, $1A, $00, $05, $96, $00, $93, $12, $01, $43, $15, $00, $0B, $13
	.byte $02, $0B, $12, $03, $0B, $14, $09, $06, $14, $0C, $09, $1A, $0C, $03, $16, $10
	.byte $00, $94, $0A, $71, $92, $09, $81, $11, $04, $0B, $91, $05, $73, $11, $09, $08
	.byte $87, $00, $AD, $01, $14, $01, $0B, $87, $02, $AA, $01, $87, $04, $A9, $05, $87
	.byte $0A, $AC, $01, $90, $0C, $93, $97, $10, $83, $96, $11, $62, $16, $14, $03, $97
	.byte $14, $93, $97, $11, $A3, $02, $13, $18, $00, $93, $19, $62, $13, $1C, $03, $94
	.byte $1C, $96, $94, $18, $86, $94, $19, $A6, $02, $0C, $0D, $43, $0F, $0C, $0B, $87
	.byte $0B, $A7, $01, $0E, $0D, $0B, $0D, $0E, $0B, $0C, $0F, $0B, $0B, $10, $0B, $8B
	.byte $11, $71, $87, $0D, $A4, $02, $87, $10, $A3, $02, $FF