; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_08 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_FREE
	.byte LEVEL4_BGBANK_INDEX(28) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $99, $01, $6A, $96, $00, $92, $12, $01, $43, $14, $0C, $09, $19, $0C, $03, $16
	.byte $10, $00, $94, $0A, $71, $91, $05, $73, $87, $00, $AC, $01, $87, $02, $AA, $01
	.byte $87, $04, $A9, $05, $87, $0A, $AC, $01, $90, $0C, $93, $94, $1F, $86, $96, $11
	.byte $62, $16, $14, $03, $97, $14, $93, $97, $11, $A3, $02, $13, $18, $00, $93, $19
	.byte $62, $13, $1C, $03, $94, $1C, $96, $94, $18, $86, $94, $19, $A6, $02, $87, $0B
	.byte $A7, $01, $8B, $11, $7E, $87, $0D, $A4, $02, $86, $10, $A4, $0F, $95, $0B, $F1
	.byte $92, $06, $F4, $13, $1F, $00, $93, $2B, $A7, $07, $71, $22, $21, $91, $24, $62
	.byte $11, $27, $03, $92, $27, $98, $92, $24, $A0, $02, $8C, $13, $F7, $87, $26, $F7
	.byte $9A, $00, $A0, $0B, $9A, $0C, $90, $13, $2A, $00, $94, $2A, $86, $07, $2B, $62
	.byte $07, $34, $A2, $07, $2C, $53, $07, $35, $93, $10, $30, $13, $91, $2E, $A1, $01
	.byte $93, $20, $A7, $06, $13, $33, $03, $94, $33, $96, $90, $2E, $61, $97, $10, $83
	.byte $10, $2D, $22, $07, $20, $44, $86, $25, $72, $0C, $35, $C2, $0C, $29, $72, $04
	.byte $2E, $32, $04, $28, $42, $83, $2B, $72, $0C, $32, $B2, $0C, $0D, $43, $0C, $2C
	.byte $82, $92, $09, $81, $14, $09, $06, $10, $48, $06, $10, $40, $06, $12, $3A, $06
	.byte $12, $3D, $06, $FF