; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18 | LEVEL2_INVERTMUSIC
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_FREE
	.byte LEVEL4_BGBANK_INDEX(3) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_ATHLETIC | LEVEL5_TIME_300

	.byte $40, $00, $0E, $75, $0A, $65, $15, $0C, $04, $76, $0C, $E4, $15, $16, $65, $95
	.byte $17, $85, $05, $15, $1D, $55, $99, $26, $81, $14, $1A, $25, $E0, $19, $25, $01
	.byte $19, $3B, $04, $7A, $3B, $E0, $37, $29, $A1, $33, $2E, $A5, $34, $35, $A4, $38
	.byte $30, $05, $38, $31, $05, $38, $32, $05, $38, $33, $05, $38, $34, $05, $75, $3F
	.byte $06, $71, $47, $02, $1A, $3E, $E0, $19, $3E, $01, $10, $4B, $01, $70, $4D, $07
	.byte $90, $4C, $80, $00, $91, $4C, $B0, $00, $14, $55, $04, $15, $55, $0A, $99, $4A
	.byte $81, $0C, $19, $49, $01, $1A, $49, $E0, $19, $57, $04, $7A, $57, $E0, $35, $4B
	.byte $22, $35, $4E, $00, $72, $61, $06, $16, $60, $01, $17, $60, $07, $92, $69, $81
	.byte $02, $FF