; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101BL	; Alternate level layout
	.word W101BO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_02 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18 | LEVEL2_INVERTMUSIC
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKLOW | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_RUINS | LEVEL5_TIME_300

	.byte $18, $05, $E2, $14, $13, $E3, $E3, $42, $10, $38, $C6, $A1, $51, $D9, $09, $EB
	.byte $42, $12, $59, $CA, $B0, $08, $58, $CB, $B0, $07, $57, $CC, $B0, $06, $56, $CD
	.byte $B0, $05, $55, $CE, $B0, $04, $54, $CF, $B0, $03, $53, $D0, $B0, $02, $52, $D1
	.byte $B0, $01, $1A, $C5, $C0, $1A, $40, $00, $B0, $46, $21, $40, $C7, $0D, $44, $CD
	.byte $03, $6C, $44, $53, $E4, $42, $10, $79, $02, $C0, $35, $07, $40, $76, $07, $80
	.byte $34, $07, $05, $72, $0A, $B0, $38, $0B, $60, $38, $12, $60, $73, $11, $80, $32
	.byte $11, $40, $31, $0A, $40, $31, $11, $05, $6A, $14, $90, $18, $12, $01, $71, $0E
	.byte $B0, $30, $0E, $40, $6C, $14, $A0, $75, $0F, $A0, $6E, $0F, $90, $25, $18, $DF
	.byte $24, $18, $41, $63, $18, $51, $77, $1D, $C0, $79, $23, $51, $1A, $23, $C0, $02
	.byte $39, $25, $60, $76, $28, $51, $75, $18, $81, $2D, $11, $42, $2C, $10, $40, $6C
	.byte $12, $51, $6F, $28, $B1, $77, $2B, $A1, $62, $2C, $90, $17, $28, $C3, $01, $72
	.byte $14, $C0, $71, $0B, $C0, $72, $0B, $C0, $76, $0F, $C0, $78, $0F, $C0, $77, $0F
	.byte $C0, $7A, $31, $C0, $76, $31, $C0, $74, $31, $C0, $73, $31, $C0, $72, $31, $C0
	.byte $21, $2A, $DE, $21, $33, $DE, $74, $38, $93, $77, $35, $C0, $77, $31, $C0, $6D
	.byte $38, $A0, $71, $1F, $C0, $15, $31, $0B, $70, $1F, $C0, $21, $28, $DD, $37, $1F
	.byte $60, $72, $22, $C0, $74, $22, $C0, $76, $22, $C0, $78, $22, $C0, $71, $2C, $C0
	.byte $13, $3D, $02, $17, $39, $00, $12, $33, $E4, $11, $25, $E2, $70, $2C, $C0, $21
	.byte $31, $DD, $71, $32, $80, $30, $32, $40, $2F, $32, $40, $FF