; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101BL	; Alternate level layout
	.word W101BO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_02 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18 | LEVEL2_INVERTMUSIC
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_RUINS | LEVEL5_TIME_300

	.byte $19, $00, $C1, $05, $15, $01, $00, $10, $0C, $E2, $11, $22, $E3, $E3, $42, $10
	.byte $38, $C6, $A1, $51, $D9, $09, $EB, $42, $12, $59, $CA, $B0, $08, $58, $CB, $B0
	.byte $07, $57, $CC, $B0, $06, $56, $CD, $B0, $05, $55, $CE, $B0, $04, $54, $CF, $B0
	.byte $03, $53, $D0, $B0, $02, $52, $D1, $B0, $01, $1A, $C5, $C0, $1A, $40, $00, $B0
	.byte $46, $10, $30, $CA, $02, $6F, $30, $52, $70, $37, $51, $11, $37, $C9, $01, $21
	.byte $40, $C7, $0D, $44, $CD, $03, $6C, $44, $53, $52, $1A, $09, $19, $19, $C1, $01
	.byte $06, $36, $B0, $E4, $42, $10, $34, $19, $0E, $39, $1B, $05, $1A, $1B, $B0, $FF