; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101AL	; Alternate level layout
	.word W101AO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_70
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_ATHLETIC | LEVEL5_TIME_300

	.byte $21, $0D, $C9, $40, $00, $B0, $C4, $24, $07, $DC, $E0, $42, $26, $EC, $71, $6C
	.byte $E8, $42, $CD, $ED, $71, $D8, $35, $08, $61, $30, $09, $60, $6A, $04, $B0, $29
	.byte $04, $40, $10, $04, $08, $35, $10, $60, $62, $09, $90, $71, $0F, $81, $2A, $14
	.byte $70, $70, $11, $A0, $62, $07, $51, $23, $07, $41, $69, $12, $81, $38, $1B, $60
	.byte $35, $18, $60, $71, $18, $81, $24, $0B, $FD, $21, $0F, $DF, $21, $12, $D7, $21
	.byte $18, $DF, $70, $1A, $C0, $6F, $1A, $C0, $6E, $1A, $C0, $62, $1A, $90, $24, $1B
	.byte $D7, $6C, $1B, $81, $21, $1D, $DD, $6F, $1D, $81, $33, $1F, $70, $33, $27, $A7
	.byte $72, $27, $51, $2B, $2C, $D5, $71, $2C, $81, $2B, $2C, $A4, $6A, $2C, $51, $38
	.byte $32, $60, $74, $32, $81, $15, $23, $09, $24, $32, $DF, $6C, $36, $B0, $2B, $36
	.byte $40, $6E, $30, $C0, $6C, $30, $C0, $6D, $30, $C0, $62, $30, $A0, $23, $1B, $41
	.byte $22, $1B, $05, $22, $2F, $05, $22, $2C, $05, $23, $2C, $43, $21, $0A, $D7, $69
	.byte $0A, $81, $6B, $0D, $A1, $07, $15, $0A, $22, $31, $05, $23, $31, $42, $22, $33
	.byte $05, $FF