; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101AL	; Alternate level layout
	.word W101AO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_07 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte 1 & %00011111 | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $20, $C3, $D8, $28, $C3, $DF, $40, $00, $B0, $C4, $21, $01, $DF, $E0, $61, $0A
	.byte $30, $5E, $13, $30, $1A, $12, $32, $5F, $10, $33, $5F, $10, $34, $5F, $10, $35
	.byte $5F, $10, $36, $5F, $12, $35, $60, $80, $2F, $63, $1F, $36, $64, $11, $35, $64
	.byte $10, $34, $64, $11, $33, $64, $11, $32, $64, $11, $36, $68, $14, $31, $68, $14
	.byte $30, $68, $14, $1A, $70, $C0, $21, $35, $70, $15, $34, $70, $15, $2F, $73, $1F
	.byte $33, $70, $85, $2F, $83, $1F, $36, $87, $A3, $38, $8D, $A1, $1A, $94, $C0, $01
	.byte $2F, $93, $1F, $39, $94, $11, $38, $94, $11, $37, $94, $11, $1A, $98, $C0, $0A
	.byte $39, $9E, $44, $38, $9F, $43, $37, $A0, $42, $36, $A1, $41, $1A, $AA, $C0, $07
	.byte $35, $AA, $14, $35, $AF, $06, $1A, $BA, $C0, $25, $35, $C1, $E1, $37, $BA, $3A
	.byte $39, $BA, $3A, $38, $BA, $3A, $40, $C5, $BF, $0A, $50, $C5, $B9, $0A, $EC, $71
	.byte $6C, $37, $81, $92, $2F, $D0, $1B, $40, $DE, $BF, $01, $50, $DE, $B9, $01, $20
	.byte $DC, $DF, $37, $D1, $92, $37, $D5, $A2, $37, $D9, $A2, $11, $D5, $0A, $E8, $42
	.byte $CD, $ED, $71, $D8, $35, $61, $06, $33, $DA, $80, $34, $DA, $80, $35, $DA, $80
	.byte $32, $DA, $80, $35, $D6, $80, $34, $D6, $80, $33, $D6, $80, $35, $D2, $80, $34
	.byte $D2, $80, $35, $65, $0A, $2F, $75, $0B, $16, $0C, $08, $54, $1C, $09, $19, $1B
	.byte $C1, $02, $11, $25, $C9, $04, $14, $2B, $C6, $02, $11, $2F, $C9, $04, $19, $39
	.byte $C1, $01, $78, $39, $51, $71, $1A, $82, $6F, $1A, $52, $30, $24, $0E, $78, $1B
	.byte $52, $38, $1C, $40, $6C, $43, $51, $0D, $43, $CD, $01, $21, $3D, $D8, $24, $35
	.byte $13, $42, $35, $11, $2F, $3E, $0B, $21, $33, $D6, $FF