; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102BL	; Alternate level layout
	.word W102BO	; Alternate object layout
	.byte LEVEL1_SIZE_13 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKLOW | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_MARIOLAND | LEVEL5_TIME_400

	.byte $58, $BC, $43, $58, $88, $43, $58, $6F, $43, $19, $00, $C1, $5C, $19, $61, $C1
	.byte $09, $0F, $62, $E3, $35, $68, $93, $19, $6E, $C1, $1E, $37, $74, $A1, $10, $72
	.byte $E2, $16, $76, $01, $35, $7C, $A3, $0D, $7F, $E2, $36, $80, $A2, $34, $84, $A4
	.byte $0E, $82, $E3, $30, $80, $12, $30, $7F, $06, $19, $90, $C1, $0A, $10, $91, $E3
	.byte $0E, $8F, $E2, $19, $9D, $C1, $32, $38, $9D, $40, $37, $9D, $40, $36, $9D, $40
	.byte $16, $9E, $01, $35, $A5, $0A, $0F, $A7, $E2, $31, $A8, $14, $35, $AE, $30, $31
	.byte $AF, $06, $0E, $AF, $E2, $10, $B1, $E3, $15, $A8, $00, $36, $B4, $A2, $35, $C0
	.byte $61, $31, $C3, $61, $2F, $C7, $86, $50, $C7, $48, $51, $C5, $B7, $01, $35, $C9
	.byte $44, $34, $CC, $40, $33, $CB, $40, $36, $CC, $40, $37, $CB, $40, $EC, $6F, $20
	.byte $E5, $D8, $70, $E6, $42, $10, $34, $14, $A4, $2E, $0B, $A4, $30, $0B, $D4, $FF