; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W104BL	; Alternate level layout
	.word W104BO	; Alternate object layout
	.byte LEVEL1_SIZE_13 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_02 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKLOW | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_400

	.byte $59, $2C, $09, $57, $2D, $09, $57, $24, $09, $19, $0A, $00, $18, $0E, $00, $16
	.byte $0D, $02, $56, $1D, $09, $49, $11, $09, $19, $00, $C1, $05, $2D, $16, $42, $EC
	.byte $63, $20, $33, $08, $10, $6F, $14, $90, $73, $11, $A0, $7A, $13, $55, $74, $11
	.byte $A0, $79, $08, $C0, $19, $15, $0B, $2E, $16, $D4, $73, $16, $81, $2F, $1A, $10
	.byte $76, $1C, $C0, $77, $0E, $50, $2E, $0A, $D3, $72, $0A, $81, $2D, $0A, $48, $6E
	.byte $10, $80, $2C, $0F, $43, $18, $0E, $B0, $7A, $09, $C0, $75, $11, $A0, $12, $09
	.byte $B0, $4D, $2A, $09, $76, $24, $50, $76, $2A, $80, $6C, $0A, $54, $13, $0F, $B1
	.byte $72, $11, $80, $10, $0D, $07, $16, $2D, $90, $19, $26, $C1, $02, $12, $01, $E3
	.byte $15, $08, $E4, $12, $1D, $E2, $17, $17, $E2, $11, $24, $E4, $7A, $15, $10, $16
	.byte $01, $01, $18, $1E, $01, $13, $32, $02, $12, $36, $02, $17, $39, $02, $18, $36
	.byte $00, $12, $2D, $E3, $74, $18, $A0, $2D, $1C, $40, $2C, $1C, $40, $2B, $1C, $40
	.byte $69, $1C, $50, $0B, $18, $B3, $0D, $13, $B2, $2C, $16, $41, $2A, $1C, $40, $2B
	.byte $0F, $40, $2A, $0F, $40, $69, $0F, $50, $2B, $17, $40, $0D, $1B, $B0, $76, $1D
	.byte $10, $75, $1D, $50, $71, $11, $10, $77, $24, $10, $78, $24, $10, $18, $27, $90
	.byte $1A, $2B, $C0, $03, $34, $29, $0F, $77, $2D, $10, $11, $12, $B1, $12, $15, $B0
	.byte $1A, $25, $B0, $38, $25, $0F, $19, $1C, $B0, $37, $1C, $0F, $14, $21, $07, $FF