; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W104AL	; Alternate level layout
	.word W104AO	; Alternate object layout
	.byte LEVEL1_SIZE_13 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_01 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_400

	.byte $19, $00, $C1, $1D, $E0, $64, $3C, $50, $09, $09, $19, $0C, $A3, $79, $0D, $C1
	.byte $38, $11, $10, $19, $12, $A2, $19, $15, $A7, $55, $18, $03, $56, $21, $03, $14
	.byte $28, $C6, $04, $73, $28, $54, $75, $31, $90, $74, $34, $90, $74, $38, $90, $75
	.byte $3B, $90, $78, $35, $A2, $78, $3A, $A0, $36, $34, $81, $15, $36, $08, $36, $37
	.byte $81, $17, $3F, $0B, $18, $3D, $C2, $03, $15, $43, $C5, $03, $19, $30, $C1, $02
	.byte $18, $30, $0B, $74, $46, $90, $2B, $33, $D4, $4A, $2E, $09, $12, $2D, $C8, $02
	.byte $4A, $25, $09, $12, $24, $C8, $02, $70, $33, $81, $55, $4C, $03, $71, $4C, $A0
	.byte $13, $1C, $E3, $13, $03, $E2, $12, $0C, $E2, $14, $11, $E4, $47, $44, $09, $47
	.byte $46, $09, $2F, $43, $44, $42, $24, $B8, $27, $6B, $42, $A0, $6B, $48, $A0, $0C
	.byte $52, $CE, $02, $55, $27, $65, $00, $59, $41, $61, $01, $6F, $46, $10, $6F, $44
	.byte $10, $13, $4B, $02, $0B, $53, $90, $18, $48, $01, $71, $4E, $A0, $76, $49, $A0
	.byte $71, $4A, $A0, $FF