; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_ALBATOSS, $0E, $55
	.byte OBJ_ALBATOSS, $10, $33
	.byte OBJ_ALBATOSS, $17, $55
	.byte OBJ_GREENTROOPA, $1B, $38
	.byte OBJ_POKEY, $1C, $2E
	.byte OBJ_ALBATOSS, $24, $56
	.byte OBJ_REDTROOPA, $2C, $01
	.byte OBJ_ALBATOSS, $30, $0E
	.byte OBJ_ALBATOSS, $34, $71
	.byte OBJ_POKEY, $36, $01
	.byte OBJ_ALBATOSS, $37, $4F
	.byte OBJ_ALBATOSS, $46, $2D
	.byte OBJ_ENDLEVELCARD, $D9, $11
	.byte $FF
