; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_CHECKPOINT_FORCE, $08, $12
	.byte OBJ_GREENTROOPA, $09, $01
	.byte OBJ_REDTROOPA, $09, $0F
	.byte OBJ_NIPPER, $10, $14
	.byte OBJ_GREENTROOPA, $1A, $01
	.byte OBJ_GREENTROOPA, $30, $01
	.byte OBJ_GREENPIRANHA, $81, $17
	.byte OBJ_GREENPIRANHA, $87, $16
	.byte OBJ_GOOMBA, $8B, $19
	.byte OBJ_GREENPIRANHA, $8D, $18
	.byte OBJ_GOOMBA, $A1, $15
	.byte OBJ_OSCILLATING_V, $A5, $19
	.byte OBJ_REDTROOPA, $B1, $19
	.byte OBJ_OSCILLATING_V, $B4, $19
	.byte OBJ_GREENPIRANHA, $D1, $17
	.byte OBJ_GREENPIRANHA, $D5, $17
	.byte OBJ_GREENPIRANHA, $D9, $17
	.byte $FF
