; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENTROOPA, $0D, $16
	.byte OBJ_ALTLEVELMOD, $54, $03
	.byte OBJ_TOUCHWARP, $54, $00
	.byte OBJ_GOOMBA, $65, $18
	.byte OBJ_GREENPIRANHA, $68, $15
	.byte OBJ_ALTLEVELMOD, $68, $04
	.byte OBJ_GOOMBA, $72, $18
	.byte OBJ_GREENPIRANHA, $74, $17
	.byte OBJ_GOOMBA, $79, $18
	.byte OBJ_GREENPIRANHA, $7C, $15
	.byte OBJ_GREENPIRANHA, $84, $14
	.byte OBJ_PARATROOPAGREENHOP, $96, $18
	.byte OBJ_GOOMBA, $A4, $18
	.byte OBJ_GOOMBA, $A6, $18
	.byte OBJ_PARATROOPAGREENHOP, $AB, $17
	.byte OBJ_PARATROOPAGREENHOP, $AE, $18
	.byte OBJ_GREENPIRANHA, $B4, $16
	.byte OBJ_GREENTROOPA, $BA, $18
	.byte OBJ_TOUCHWARP, $CF, $04
	.byte $FF
