; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_PARATROOPAGREENHOP, $08, $12
	.byte OBJ_PARATROOPAGREENHOP, $14, $0E
	.byte OBJ_PARATROOPAGREENHOP, $1A, $0E
	.byte OBJ_ENDLEVELCARD, $2A, $0E
	.byte $FF
