; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_ENDLEVELCARD, $09, $10
	.byte OBJ_GREENTROOPA, $25, $11
	.byte OBJ_REDTROOPA, $45, $0E
	.byte OBJ_GREENTROOPA, $67, $18
	.byte OBJ_GOOMBA, $6D, $18
	.byte OBJ_GOOMBA, $6F, $18
	.byte OBJ_GOOMBA, $71, $18
	.byte OBJ_GREENTROOPA, $83, $18
	.byte OBJ_GREENTROOPA, $85, $18
	.byte OBJ_GREENTROOPA, $87, $18
	.byte OBJ_GREENTROOPA, $8E, $18
	.byte OBJ_GREENTROOPA, $90, $18
	.byte OBJ_GREENTROOPA, $98, $18
	.byte OBJ_GREENTROOPA, $9A, $18
	.byte OBJ_GREENTROOPA, $9C, $18
	.byte OBJ_GREENPIRANHA, $9E, $16
	.byte OBJ_GOOMBA, $A4, $18
	.byte OBJ_GOOMBA, $A6, $18
	.byte OBJ_GOOMBA, $A8, $18
	.byte $FF
