; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_ENDLEVELCARD, $09, $10
	.byte OBJ_PINATA, $23, $08
	.byte OBJ_GREENTROOPA, $25, $11
	.byte OBJ_REDTROOPA, $45, $0E
	.byte OBJ_PINATA, $54, $0A
	.byte OBJ_PINATA, $62, $0A
	.byte OBJ_PINATA, $69, $0C
	.byte OBJ_PINATA, $7B, $0C
	.byte $FF
