; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0B
	.byte OBJ_SPRING, $02, $17
	.byte OBJ_CRATE, $06, $10
	.byte OBJ_SPRING, $12, $0E
	.byte OBJ_GREENTROOPA, $16, $16
	.byte OBJ_CRATE, $16, $2C
	.byte OBJ_CRATE, $23, $0C
	.byte OBJ_CRATE, $25, $0D
	.byte OBJ_SPRING, $2E, $0E
	.byte OBJ_CRATE, $3D, $01
	.byte OBJ_CRATE, $48, $01
	.byte OBJ_BOOMBOOMFLY, $71, $12
	.byte $FF
