; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_SPRING, $07, $15
	.byte OBJ_THWOMP, $08, $10
	.byte OBJ_DRYBONES, $51, $16
	.byte OBJ_THWOMP, $5A, $10
	.byte OBJ_DRYBONES, $61, $16
	.byte OBJ_THWOMP, $7D, $10
	.byte OBJ_CHECKPOINT, $8C, $15
	.byte OBJ_GOOMBA, $90, $16
	.byte OBJ_GOOMBA, $93, $16
	.byte OBJ_GOOMBA, $96, $16
	.byte OBJ_PODOBOO, $AD, $14
	.byte OBJ_PODOBOO, $BB, $14
	.byte OBJ_CFIRE_BULLETBILL, $C9, $18
	.byte OBJ_CFIRE_BULLETBILL, $D4, $18
	.byte OBJ_PODOBOO, $E1, $13
	.byte OBJ_PODOBOO, $E5, $13
	.byte $FF
