; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ALTLEVELMOD, $31, $00
	.byte OBJ_ALTLEVELMOD, $55, $00
	.byte OBJ_ALTLEVELMOD, $80, $00
	.byte OBJ_ALTLEVELMOD, $94, $00
	.byte OBJ_ALTLEVELMOD, $BA, $00
	.byte OBJ_ALTLEVELMOD, $CB, $06
	.byte OBJ_ALTLEVELMOD, $DE, $00
	.byte $FF
