; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_KURIBO, $09, $18
	.byte OBJ_KURIBO, $14, $15
	.byte OBJ_SPRING, $19, $12
	.byte OBJ_CRATE, $1B, $12
	.byte $FF
